# Generated by Django 3.0.3 on 2020-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
